export const DINO_ROSTER = [
  {
    id: "bruno-bronto",
    name: "Bruno Bronto",
    speciesId: "brachiosaurus-altithorax",
    species: "Brachiosaurus",
    germanName: "Brachiosaurus",
    scientificName: "Brachiosaurus altithorax",
    shortLabel: "Langhals",
    imageAsset: "rewards/dinos/dino-bruno-bronto.svg",
    audioFile: "brachiosaurus-altithorax.wav",
    videoFile: "Brachiosaurus.mp4",
    animation: "bronto-step",
    motion: "gentle-walk",
    theme: "green",
    praise: "Bruno macht lange Hälse vor Freude. Du hast richtig stark gerechnet!",
    unlockText: "Bruno Bronto kommt in deine Sammlung!",
    shortText: "Bruno macht lange Hälse vor Freude.",
  },
  {
    id: "trixi-triceratops",
    name: "Trixi Triceratops",
    speciesId: "triceratops-horridus",
    species: "Triceratops",
    germanName: "Triceratops",
    scientificName: "Triceratops horridus",
    shortLabel: "Dreihorn",
    imageAsset: "rewards/dinos/dino-trixi-triceratops.svg",
    audioFile: "triceratops-horridus.wav",
    videoFile: "Triceratops.mp4",
    animation: "trixi-stomp",
    motion: "stomp",
    theme: "orange",
    praise: "Trixi stampft vor Begeisterung. Eine perfekte Runde!",
    unlockText: "Trixi Triceratops gehört jetzt zu dir!",
    shortText: "Trixi stampft vor Begeisterung.",
  },
  {
    id: "pico-pteranodon",
    name: "Pico Pteranodon",
    speciesId: "pteranodon-longiceps",
    species: "Pteranodon",
    germanName: "Pteranodon",
    scientificName: "Pteranodon longiceps",
    shortLabel: "Flugsaurier",
    imageAsset: "rewards/dinos/dino-pico-pteranodon.svg",
    audioFile: "pteranodon-longiceps.wav",
    videoFile: "Pteranodon.mp4",
    animation: "pico-fly",
    motion: "wing-float",
    theme: "blue",
    praise: "Pico flattert los. Deine Zahlen fliegen!",
    unlockText: "Pico Pteranodon fliegt in deine Sammlung!",
    shortText: "Pico schwebt durch die Sammlung.",
  },
  {
    id: "paula-parasaurolophus",
    name: "Paula Parasaurolophus",
    speciesId: "parasaurolophus-walkeri",
    species: "Parasaurolophus",
    germanName: "Parasaurolophus",
    scientificName: "Parasaurolophus walkeri",
    shortLabel: "Kamm-Dino",
    imageAsset: "",
    audioFile: "parasaurolophus-walkeri.wav",
    videoFile: "Parasaurolophus.mp4",
    animation: "parasauro-prance",
    motion: "gentle-walk",
    theme: "amber",
    praise: "Paula trägt ihren Kamm ganz stolz. Das war eine starke Runde!",
    unlockText: "Paula Parasaurolophus ist jetzt in deiner Sammlung!",
    shortText: "Paula nickt fröhlich mit ihrem Kamm.",
  },
  {
    id: "vito-velociraptor",
    name: "Vito Velociraptor",
    speciesId: "velociraptor-mongoliensis",
    species: "Velociraptor",
    germanName: "Velociraptor",
    scientificName: "Velociraptor mongoliensis",
    shortLabel: "Feder-Räuber",
    imageAsset: "",
    audioFile: "velociraptor-mongoliensis.wav",
    videoFile: "Trodon.mp4",
    animation: "raptor-prance",
    motion: "stomp",
    theme: "teal",
    praise: "Vito stellt seine Krallen auf. Du hast blitzschnell gerechnet!",
    unlockText: "Vito Velociraptor ist jetzt freigeschaltet!",
    shortText: "Vito tänzelt blitzschnell vor Freude.",
  },
  {
    id: "nora-nadelruecken",
    name: "Nora Nadelrücken",
    speciesId: "stegosaurus-stenops",
    species: "Stegosaurus",
    germanName: "Stegosaurus",
    scientificName: "Stegosaurus stenops",
    shortLabel: "Plattenrücken",
    imageAsset: "",
    audioFile: "stegosaurus-stenops.wav",
    videoFile: "Stegosaurus.mp4",
    animation: "nora-wiggle",
    motion: "gentle-walk",
    theme: "violet",
    praise: "Nora wackelt mit ihren Rückenplatten. Das war schildkrötenstark!",
    unlockText: "Nora Nadelrücken ist jetzt in deiner Sammlung!",
    shortText: "Nora wackelt mit ihren Rückenplatten.",
  },
  {
    id: "roxi-rex",
    name: "Roxi Rex",
    speciesId: "tyrannosaurus-rex",
    species: "Tyrannosaurus",
    germanName: "Tyrannosaurus",
    scientificName: "Tyrannosaurus rex",
    shortLabel: "T-Rex",
    imageAsset: "",
    audioFile: "tyrannosaurus-rex.wav",
    videoFile: "T-Rex.mp4",
    animation: "roxi-roar",
    motion: "stomp",
    theme: "red",
    praise: "Roxi zeigt ihre Zähne und freut sich riesig. Zehn von zehn!",
    unlockText: "Roxi Rex stampft in deine Sammlung!",
    shortText: "Roxi brüllt begeistert los.",
  },
  {
    id: "eulo-euoplocephalus",
    name: "Eulo Euoplocephalus",
    speciesId: "euoplocephalus-tutus",
    species: "Euoplocephalus",
    germanName: "Euoplocephalus",
    scientificName: "Euoplocephalus tutus",
    shortLabel: "Keulenschwanz",
    imageAsset: "",
    audioFile: "euoplocephalus-tutus.wav",
    videoFile: "Euoplocephalus.mp4",
    animation: "eulo-sway",
    motion: "gentle-walk",
    theme: "mint",
    praise: "Eulo schwingt fröhlich seine Schwanzkeule. Ganz stark gerechnet!",
    unlockText: "Eulo Euoplocephalus ist jetzt freigeschaltet!",
    shortText: "Eulo schwingt fröhlich seine Schwanzkeule.",
  },
];
